// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA79yQBaEyqN7d4VTBjl9SPFW78HGCIIxw',
    appId: '1:786084899455:web:cce1d347ef1ef26ee72d4a',
    messagingSenderId: '786084899455',
    projectId: 'unified-cc5c8',
    authDomain: 'unified-cc5c8.firebaseapp.com',
    storageBucket: 'unified-cc5c8.firebasestorage.app',
    measurementId: 'G-SKX9347YXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvLJjiSB17c1FPoR7NBz_3JIOnGLE8jfc',
    appId: '1:786084899455:android:2f5629b2d76363c6e72d4a',
    messagingSenderId: '786084899455',
    projectId: 'unified-cc5c8',
    storageBucket: 'unified-cc5c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBDcwhmyKy5qOc7CZS0dd7jM1T1q2b61c',
    appId: '1:786084899455:ios:5b9bd8c89d55856be72d4a',
    messagingSenderId: '786084899455',
    projectId: 'unified-cc5c8',
    storageBucket: 'unified-cc5c8.firebasestorage.app',
    iosBundleId: 'com.example.unified',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBDcwhmyKy5qOc7CZS0dd7jM1T1q2b61c',
    appId: '1:786084899455:ios:5b9bd8c89d55856be72d4a',
    messagingSenderId: '786084899455',
    projectId: 'unified-cc5c8',
    storageBucket: 'unified-cc5c8.firebasestorage.app',
    iosBundleId: 'com.example.unified',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA79yQBaEyqN7d4VTBjl9SPFW78HGCIIxw',
    appId: '1:786084899455:web:77ea78d07a4198f8e72d4a',
    messagingSenderId: '786084899455',
    projectId: 'unified-cc5c8',
    authDomain: 'unified-cc5c8.firebaseapp.com',
    storageBucket: 'unified-cc5c8.firebasestorage.app',
    measurementId: 'G-25NLZ438B7',
  );
}
